-- schema for Noctis
CREATE TABLE users (id BIGINT PRIMARY KEY,is_bot BOOLEAN DEFAULT FALSE,is_deleted BOOLEAN DEFAULT FALSE,first_name VARCHAR(255),last_name VARCHAR(255),username VARCHAR(255),language_code VARCHAR(10),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_username (username));
CREATE TABLE chats (id BIGINT PRIMARY KEY,title VARCHAR(255) NOT NULL,username VARCHAR(255),type VARCHAR(20) DEFAULT 'supergroup',settings JSON,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE members (user_id BIGINT NOT NULL,chat_id BIGINT NOT NULL,status VARCHAR(20) DEFAULT 'member',joined_date TIMESTAMP,xp INT DEFAULT 0,level INT DEFAULT 0,reputation INT DEFAULT 0,custom_rank VARCHAR(100),last_active TIMESTAMP,message_count INT DEFAULT 0,PRIMARY KEY (user_id, chat_id),INDEX idx_chat_status (chat_id, status),INDEX idx_xp (chat_id, xp),INDEX idx_reputation (chat_id, reputation));
CREATE TABLE warnings (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,chat_id BIGINT NOT NULL,admin_id BIGINT NOT NULL,reason TEXT,warning_count INT DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE messages (id BIGINT PRIMARY KEY,user_id BIGINT NOT NULL,chat_id BIGINT NOT NULL,message_text TEXT,message_date TIMESTAMP NOT NULL,is_forwarded BOOLEAN DEFAULT FALSE,has_media BOOLEAN DEFAULT FALSE,media_type VARCHAR(50),reply_to_message_id BIGINT);
CREATE TABLE triggers (id BIGSERIAL PRIMARY KEY,chat_id BIGINT NOT NULL,trigger_type VARCHAR(20) DEFAULT 'contains',trigger_text VARCHAR(500) NOT NULL,action_type VARCHAR(200) NOT NULL,action_value VARCHAR(500),priority INT DEFAULT 0,is_active BOOLEAN DEFAULT TRUE,created_by BIGINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE schedules (id BIGSERIAL PRIMARY KEY,chat_id BIGINT NOT NULL,message TEXT NOT NULL,schedule_type VARCHAR(20) NOT NULL,schedule_value VARCHAR(100),next_run TIMESTAMP NOT NULL,is_active BOOLEAN DEFAULT TRUE,last_run TIMESTAMP,created_by BIGINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE chat_settings (chat_id BIGINT PRIMARY KEY,welcome_enabled BOOLEAN DEFAULT FALSE,welcome_message TEXT,welcome_image_file_id VARCHAR(255),captcha_enabled BOOLEAN DEFAULT FALSE,captcha_type VARCHAR(20) DEFAULT 'button',auto_delete_duration INT,anti_spam_level INT DEFAULT 2,warn_limit INT DEFAULT 3,warn_action VARCHAR(20) DEFAULT 'ban',levels_enabled BOOLEAN DEFAULT FALSE,level_up_message TEXT,reputation_enabled BOOLEAN DEFAULT FALSE,rep_cooldown INT DEFAULT 900,rep_triggers JSON);
CREATE TABLE xp_log (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,chat_id BIGINT NOT NULL,xp_earned INT NOT NULL,source VARCHAR(20) DEFAULT 'message',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE bans (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL,chat_id BIGINT NOT NULL,admin_id BIGINT NOT NULL,reason TEXT,expires_at TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE whitelist (user_id BIGINT NOT NULL,chat_id BIGINT NOT NULL,added_by BIGINT,added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (user_id, chat_id));
CREATE TABLE activity_log (id BIGSERIAL PRIMARY KEY,chat_id BIGINT NOT NULL,user_id BIGINT NOT NULL,hour_of_day INT NOT NULL,date DATE NOT NULL,count INT DEFAULT 1);
